-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Chunk000
import Snaky.Gen17.Chunk001
import Snaky.Gen17.Chunk002
import Snaky.Gen17.Chunk003
import Snaky.Gen17.Chunk004
import Snaky.Gen17.Chunk005
import Snaky.Gen17.Chunk006
import Snaky.Gen17.Chunk007
import Snaky.Gen17.Chunk008
import Snaky.Gen17.Chunk009
import Snaky.Gen17.Chunk010
import Snaky.Gen17.Chunk011
import Snaky.Gen17.Chunk012
import Snaky.Gen17.Chunk013
import Snaky.Gen17.Chunk014
import Snaky.Gen17.Chunk015
import Snaky.Gen17.Chunk016
import Snaky.Gen17.Chunk017
import Snaky.Gen17.Chunk018
import Snaky.Gen17.Chunk019
import Snaky.Gen17.Chunk020
import Snaky.Gen17.Chunk021
import Snaky.Gen17.Chunk022
import Snaky.Gen17.Chunk023
import Snaky.Gen17.Chunk024
import Snaky.Gen17.Chunk025
import Snaky.Gen17.Chunk026
import Snaky.Gen17.Chunk027
import Snaky.Gen17.Chunk028
import Snaky.Gen17.Chunk029
import Snaky.Gen17.Chunk030
import Snaky.Gen17.Chunk031
import Snaky.Gen17.Chunk032
import Snaky.Gen17.Chunk033
import Snaky.Gen17.Chunk034
import Snaky.Gen17.Chunk035
import Snaky.Gen17.Chunk036
import Snaky.Gen17.Chunk037
import Snaky.Gen17.Chunk038
import Snaky.Gen17.Chunk039
import Snaky.Gen17.Chunk040
import Snaky.CardsSound

namespace Snaky.Gen17

/-- Every card in the lookup tree is justified. -/
theorem tree_ok : tree.all (cardOK getK) = true := (CTree.all_node (CTree.all_node (CTree.all_node (CTree.all_node (CTree.all_node t0_ok t1_ok) (CTree.all_node t2_ok (CTree.all_node t3_ok t4_ok))) (CTree.all_node (CTree.all_node t5_ok t6_ok) (CTree.all_node t7_ok (CTree.all_node t8_ok t9_ok)))) (CTree.all_node (CTree.all_node (CTree.all_node t10_ok t11_ok) (CTree.all_node t12_ok (CTree.all_node t13_ok t14_ok))) (CTree.all_node (CTree.all_node t15_ok t16_ok) (CTree.all_node t17_ok (CTree.all_node t18_ok t19_ok))))) (CTree.all_node (CTree.all_node (CTree.all_node (CTree.all_node t20_ok t21_ok) (CTree.all_node t22_ok (CTree.all_node t23_ok t24_ok))) (CTree.all_node (CTree.all_node t25_ok t26_ok) (CTree.all_node t27_ok (CTree.all_node t28_ok t29_ok)))) (CTree.all_node (CTree.all_node (CTree.all_node t30_ok t31_ok) (CTree.all_node t32_ok (CTree.all_node t33_ok t34_ok))) (CTree.all_node (CTree.all_node t35_ok (CTree.all_node t36_ok t37_ok)) (CTree.all_node t38_ok (CTree.all_node t39_ok t40_ok))))))

/-- The root card 1737 has `A = []` and fits on the 17 × 17 board. -/
theorem root_ok : rootOK getK 17 17 1737 ⟨1, 0, 0, 1, 0, 0⟩ = true := by decide +kernel

end Snaky.Gen17
