-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Tree

namespace Snaky.Gen17

def c1737_part2 : List Pt := [(2, 10), (2, 11), (2, 12), (2, 13), (2, 14), (2, 15), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (3, 9)]

set_option maxHeartbeats 0 in
/-- Card 1737: White replies at 15 cells of its region (piece 3 of 17). -/
theorem c1737_r2 : c1737_part2.all (replyOK getK c1737) = true := by decide +kernel

end Snaky.Gen17
