-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Tree

namespace Snaky.Gen17

def c1736_part8 : List Pt := [(8, 13), (8, 14), (8, 15), (8, 16), (9, 0), (9, 1), (9, 2), (9, 3), (9, 4), (9, 5), (9, 6), (9, 7), (9, 8), (9, 9), (9, 10)]

set_option maxHeartbeats 0 in
/-- Card 1736: White replies at 15 cells of its region (piece 9 of 15). -/
theorem c1736_r8 : c1736_part8.all (replyOK getK c1736) = true := by decide +kernel

end Snaky.Gen17
