-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Tree

namespace Snaky.Gen17

def c1737_part10 : List Pt := [(9, 16), (10, 0), (10, 1), (10, 2), (10, 3), (10, 4), (10, 5), (10, 6), (10, 7), (10, 8), (10, 9), (10, 10), (10, 11), (10, 12), (10, 13)]

set_option maxHeartbeats 0 in
/-- Card 1737: White replies at 15 cells of its region (piece 11 of 17). -/
theorem c1737_r10 : c1737_part10.all (replyOK getK c1737) = true := by decide +kernel

end Snaky.Gen17
