-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Chunk040Head
import Snaky.Gen17.Chunk040R0
import Snaky.Gen17.Chunk040R1
import Snaky.Gen17.Chunk040R2
import Snaky.Gen17.Chunk040R3
import Snaky.Gen17.Chunk040R4
import Snaky.Gen17.Chunk040R5
import Snaky.Gen17.Chunk040R6
import Snaky.Gen17.Chunk040R7
import Snaky.Gen17.Chunk040R8
import Snaky.Gen17.Chunk040R9
import Snaky.Gen17.Chunk040R10
import Snaky.Gen17.Chunk040R11
import Snaky.Gen17.Chunk040R12
import Snaky.Gen17.Chunk040R13
import Snaky.Gen17.Chunk040R14
import Snaky.Gen17.Chunk040R15
import Snaky.Gen17.Chunk040R16
import Snaky.CardsSound

namespace Snaky.Gen17

/-- Card 1737 is justified (checked in 18 pieces). -/
theorem t40_ok : t40.all (cardOK getK) = true :=
  CTree.all_leaf (cardOK_of_split (c1737_part0 ++ c1737_part1 ++ c1737_part2 ++ c1737_part3 ++ c1737_part4 ++ c1737_part5 ++ c1737_part6 ++ c1737_part7 ++ c1737_part8 ++ c1737_part9 ++ c1737_part10 ++ c1737_part11 ++ c1737_part12 ++ c1737_part13 ++ c1737_part14 ++ c1737_part15 ++ c1737_part16) c1737_head (by decide +kernel)
    (by simp only [List.all_append, c1737_r0, c1737_r1, c1737_r2, c1737_r3, c1737_r4, c1737_r5, c1737_r6, c1737_r7, c1737_r8, c1737_r9, c1737_r10, c1737_r11, c1737_r12, c1737_r13, c1737_r14, c1737_r15, c1737_r16, Bool.and_self]))

end Snaky.Gen17
