-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Tree

namespace Snaky.Gen17

def c1736_part5 : List Pt := [(5, 15), (6, 0), (6, 1), (6, 2), (6, 3), (6, 4), (6, 5), (6, 6), (6, 7), (6, 8), (6, 9), (6, 10), (6, 11), (6, 12), (6, 13)]

set_option maxHeartbeats 0 in
/-- Card 1736: White replies at 15 cells of its region (piece 6 of 15). -/
theorem c1736_r5 : c1736_part5.all (replyOK getK c1736) = true := by decide +kernel

end Snaky.Gen17
