-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Tree

namespace Snaky.Gen17

def c1737_part0 : List Pt := [(0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9), (0, 10), (0, 11), (0, 12), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8)]

set_option maxHeartbeats 0 in
/-- Card 1737: White replies at 15 cells of its region (piece 1 of 17). -/
theorem c1737_r0 : c1737_part0.all (replyOK getK c1737) = true := by decide +kernel

end Snaky.Gen17
