-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Tree

namespace Snaky.Gen17

def c1737_part9 : List Pt := [(9, 1), (9, 2), (9, 3), (9, 4), (9, 5), (9, 6), (9, 7), (9, 8), (9, 9), (9, 10), (9, 11), (9, 12), (9, 13), (9, 14), (9, 15)]

set_option maxHeartbeats 0 in
/-- Card 1737: White replies at 15 cells of its region (piece 10 of 17). -/
theorem c1737_r9 : c1737_part9.all (replyOK getK c1737) = true := by decide +kernel

end Snaky.Gen17
