-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Tree

namespace Snaky.Gen17

def c1737_part13 : List Pt := [(12, 10), (12, 11), (12, 12), (12, 13), (12, 14), (12, 15), (13, 1), (13, 2), (13, 3), (13, 4), (13, 5), (13, 6), (13, 7), (13, 8), (13, 9)]

set_option maxHeartbeats 0 in
/-- Card 1737: White replies at 15 cells of its region (piece 14 of 17). -/
theorem c1737_r13 : c1737_part13.all (replyOK getK c1737) = true := by decide +kernel

end Snaky.Gen17
