-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Tree

namespace Snaky.Gen17

def c1737_part5 : List Pt := [(5, 8), (5, 9), (5, 10), (5, 11), (5, 12), (5, 13), (5, 14), (5, 15), (5, 16), (6, 0), (6, 1), (6, 2), (6, 3), (6, 4), (6, 5)]

set_option maxHeartbeats 0 in
/-- Card 1737: White replies at 15 cells of its region (piece 6 of 17). -/
theorem c1737_r5 : c1737_part5.all (replyOK getK c1737) = true := by decide +kernel

end Snaky.Gen17
