-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Tree

namespace Snaky.Gen17

def c1736_part4 : List Pt := [(5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (5, 8), (5, 9), (5, 10), (5, 11), (5, 12), (5, 13), (5, 14)]

set_option maxHeartbeats 0 in
/-- Card 1736: White replies at 15 cells of its region (piece 5 of 15). -/
theorem c1736_r4 : c1736_part4.all (replyOK getK c1736) = true := by decide +kernel

end Snaky.Gen17
