-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Tree

namespace Snaky.Gen17

def c1736_part11 : List Pt := [(11, 8), (11, 9), (11, 10), (11, 11), (11, 12), (11, 13), (11, 14), (11, 15), (12, 1), (12, 2), (12, 3), (12, 4), (12, 5), (12, 6), (12, 7)]

set_option maxHeartbeats 0 in
/-- Card 1736: White replies at 15 cells of its region (piece 12 of 15). -/
theorem c1736_r11 : c1736_part11.all (replyOK getK c1736) = true := by decide +kernel

end Snaky.Gen17
