-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Tree

namespace Snaky.Gen17

set_option maxHeartbeats 0 in
/-- Cards 1013-1060 are justified. -/
theorem t21_ok : t21.all (cardOK getK) = true := by decide +kernel

end Snaky.Gen17
