-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Tree

namespace Snaky.Gen17

def c1736_part10 : List Pt := [(10, 9), (10, 10), (10, 11), (10, 12), (10, 13), (10, 14), (10, 15), (11, 0), (11, 1), (11, 2), (11, 3), (11, 4), (11, 5), (11, 6), (11, 7)]

set_option maxHeartbeats 0 in
/-- Card 1736: White replies at 15 cells of its region (piece 11 of 15). -/
theorem c1736_r10 : c1736_part10.all (replyOK getK c1736) = true := by decide +kernel

end Snaky.Gen17
