-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Tree

namespace Snaky.Gen17

def c1736_part2 : List Pt := [(2, 15), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (3, 9), (3, 10), (3, 11), (3, 12), (3, 13), (3, 14), (3, 15)]

set_option maxHeartbeats 0 in
/-- Card 1736: White replies at 15 cells of its region (piece 3 of 15). -/
theorem c1736_r2 : c1736_part2.all (replyOK getK c1736) = true := by decide +kernel

end Snaky.Gen17
