-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Tree

namespace Snaky.Gen17

set_option maxHeartbeats 0 in
/-- Card 1736: move, height, and pass hint. -/
theorem c1736_head : cardHead getK c1736 = true := by decide +kernel

end Snaky.Gen17
