-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Tree

namespace Snaky.Gen17

set_option maxHeartbeats 0 in
/-- Cards 882-892 are justified. -/
theorem t18_ok : t18.all (cardOK getK) = true := by decide +kernel

end Snaky.Gen17
