-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Tree

namespace Snaky.Gen17

def c1736_part14 : List Pt := [(14, 10), (14, 11), (14, 12), (15, 5), (15, 6), (15, 7), (15, 8), (15, 9), (15, 10), (15, 11), (16, 6), (16, 8), (16, 10), (7, 8), (8, 8)]

set_option maxHeartbeats 0 in
/-- Card 1736: White replies at 15 cells of its region (piece 15 of 15). -/
theorem c1736_r14 : c1736_part14.all (replyOK getK c1736) = true := by decide +kernel

end Snaky.Gen17
