-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Tree

namespace Snaky.Gen17

def c1737_part4 : List Pt := [(4, 10), (4, 11), (4, 12), (4, 13), (4, 14), (4, 15), (4, 16), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7)]

set_option maxHeartbeats 0 in
/-- Card 1737: White replies at 15 cells of its region (piece 5 of 17). -/
theorem c1737_r4 : c1737_part4.all (replyOK getK c1737) = true := by decide +kernel

end Snaky.Gen17
