-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Tree

namespace Snaky.Gen17

def c1736_part1 : List Pt := [(1, 11), (1, 12), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (2, 9), (2, 10), (2, 11), (2, 12), (2, 13), (2, 14)]

set_option maxHeartbeats 0 in
/-- Card 1736: White replies at 15 cells of its region (piece 2 of 15). -/
theorem c1736_r1 : c1736_part1.all (replyOK getK c1736) = true := by decide +kernel

end Snaky.Gen17
