-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Tree

namespace Snaky.Gen17

def c1737_part11 : List Pt := [(10, 14), (10, 15), (10, 16), (11, 0), (11, 1), (11, 2), (11, 3), (11, 4), (11, 5), (11, 6), (11, 7), (11, 8), (11, 9), (11, 10), (11, 11)]

set_option maxHeartbeats 0 in
/-- Card 1737: White replies at 15 cells of its region (piece 12 of 17). -/
theorem c1737_r11 : c1737_part11.all (replyOK getK c1737) = true := by decide +kernel

end Snaky.Gen17
