-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Tree

namespace Snaky.Gen17

set_option maxHeartbeats 0 in
/-- Cards 526-585 are justified. -/
theorem t9_ok : t9.all (cardOK getK) = true := by decide +kernel

end Snaky.Gen17
