-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Tree

namespace Snaky.Gen17

def c1737_part15 : List Pt := [(14, 11), (14, 12), (14, 13), (14, 14), (14, 15), (15, 2), (15, 3), (15, 4), (15, 5), (15, 6), (15, 7), (15, 8), (15, 9), (15, 10), (15, 11)]

set_option maxHeartbeats 0 in
/-- Card 1737: White replies at 15 cells of its region (piece 16 of 17). -/
theorem c1737_r15 : c1737_part15.all (replyOK getK c1737) = true := by decide +kernel

end Snaky.Gen17
