-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Tree

namespace Snaky.Gen17

def c1736_part6 : List Pt := [(6, 14), (6, 15), (6, 16), (7, 0), (7, 1), (7, 2), (7, 3), (7, 4), (7, 5), (7, 6), (7, 7), (7, 9), (7, 10), (7, 11), (7, 12)]

set_option maxHeartbeats 0 in
/-- Card 1736: White replies at 15 cells of its region (piece 7 of 15). -/
theorem c1736_r6 : c1736_part6.all (replyOK getK c1736) = true := by decide +kernel

end Snaky.Gen17
