-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Tree

namespace Snaky.Gen17

def c1737_part16 : List Pt := [(15, 12), (15, 13), (16, 5), (16, 6), (16, 7), (16, 8), (16, 9), (16, 10), (16, 11), (16, 12), (8, 8)]

set_option maxHeartbeats 0 in
/-- Card 1737: White replies at 11 cells of its region (piece 17 of 17). -/
theorem c1737_r16 : c1737_part16.all (replyOK getK c1737) = true := by decide +kernel

end Snaky.Gen17
