-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Tree

namespace Snaky.Gen17

def c1736_part12 : List Pt := [(12, 8), (12, 9), (12, 10), (12, 11), (12, 12), (12, 13), (12, 14), (12, 15), (13, 1), (13, 2), (13, 3), (13, 4), (13, 5), (13, 6), (13, 7)]

set_option maxHeartbeats 0 in
/-- Card 1736: White replies at 15 cells of its region (piece 13 of 15). -/
theorem c1736_r12 : c1736_part12.all (replyOK getK c1736) = true := by decide +kernel

end Snaky.Gen17
