-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Tree

namespace Snaky.Gen17

def c1737_part12 : List Pt := [(11, 12), (11, 13), (11, 14), (11, 15), (11, 16), (12, 0), (12, 1), (12, 2), (12, 3), (12, 4), (12, 5), (12, 6), (12, 7), (12, 8), (12, 9)]

set_option maxHeartbeats 0 in
/-- Card 1737: White replies at 15 cells of its region (piece 13 of 17). -/
theorem c1737_r12 : c1737_part12.all (replyOK getK c1737) = true := by decide +kernel

end Snaky.Gen17
