-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Tree

namespace Snaky.Gen17

def c1737_part3 : List Pt := [(3, 10), (3, 11), (3, 12), (3, 13), (3, 14), (3, 15), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (4, 8), (4, 9)]

set_option maxHeartbeats 0 in
/-- Card 1737: White replies at 15 cells of its region (piece 4 of 17). -/
theorem c1737_r3 : c1737_part3.all (replyOK getK c1737) = true := by decide +kernel

end Snaky.Gen17
