-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Tree

namespace Snaky.Gen17

def c1736_part9 : List Pt := [(9, 11), (9, 12), (9, 13), (9, 14), (9, 15), (9, 16), (10, 0), (10, 1), (10, 2), (10, 3), (10, 4), (10, 5), (10, 6), (10, 7), (10, 8)]

set_option maxHeartbeats 0 in
/-- Card 1736: White replies at 15 cells of its region (piece 10 of 15). -/
theorem c1736_r9 : c1736_part9.all (replyOK getK c1736) = true := by decide +kernel

end Snaky.Gen17
