-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Tree

namespace Snaky.Gen17

def c1737_part6 : List Pt := [(6, 6), (6, 7), (6, 8), (6, 9), (6, 10), (6, 11), (6, 12), (6, 13), (6, 14), (6, 15), (6, 16), (7, 0), (7, 1), (7, 2), (7, 3)]

set_option maxHeartbeats 0 in
/-- Card 1737: White replies at 15 cells of its region (piece 7 of 17). -/
theorem c1737_r6 : c1737_part6.all (replyOK getK c1737) = true := by decide +kernel

end Snaky.Gen17
