-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Tree

namespace Snaky.Gen17

def c1736_part7 : List Pt := [(7, 13), (7, 14), (7, 15), (7, 16), (8, 0), (8, 1), (8, 2), (8, 3), (8, 4), (8, 5), (8, 6), (8, 7), (8, 10), (8, 11), (8, 12)]

set_option maxHeartbeats 0 in
/-- Card 1736: White replies at 15 cells of its region (piece 8 of 15). -/
theorem c1736_r7 : c1736_part7.all (replyOK getK c1736) = true := by decide +kernel

end Snaky.Gen17
