-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Tree

namespace Snaky.Gen17

def c1737_part14 : List Pt := [(13, 10), (13, 11), (13, 12), (13, 13), (13, 14), (13, 15), (14, 2), (14, 3), (14, 4), (14, 5), (14, 6), (14, 7), (14, 8), (14, 9), (14, 10)]

set_option maxHeartbeats 0 in
/-- Card 1737: White replies at 15 cells of its region (piece 15 of 17). -/
theorem c1737_r14 : c1737_part14.all (replyOK getK c1737) = true := by decide +kernel

end Snaky.Gen17
