-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Tree

namespace Snaky.Gen17

def c1737_part8 : List Pt := [(8, 2), (8, 3), (8, 4), (8, 5), (8, 6), (8, 7), (8, 9), (8, 10), (8, 11), (8, 12), (8, 13), (8, 14), (8, 15), (8, 16), (9, 0)]

set_option maxHeartbeats 0 in
/-- Card 1737: White replies at 15 cells of its region (piece 9 of 17). -/
theorem c1737_r8 : c1737_part8.all (replyOK getK c1737) = true := by decide +kernel

end Snaky.Gen17
