-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Tree

namespace Snaky.Gen17

def c1736_part13 : List Pt := [(13, 8), (13, 9), (13, 10), (13, 11), (13, 12), (13, 13), (13, 14), (14, 1), (14, 3), (14, 4), (14, 5), (14, 6), (14, 7), (14, 8), (14, 9)]

set_option maxHeartbeats 0 in
/-- Card 1736: White replies at 15 cells of its region (piece 14 of 15). -/
theorem c1736_r13 : c1736_part13.all (replyOK getK c1736) = true := by decide +kernel

end Snaky.Gen17
