-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Chunk039Head
import Snaky.Gen17.Chunk039R0
import Snaky.Gen17.Chunk039R1
import Snaky.Gen17.Chunk039R2
import Snaky.Gen17.Chunk039R3
import Snaky.Gen17.Chunk039R4
import Snaky.Gen17.Chunk039R5
import Snaky.Gen17.Chunk039R6
import Snaky.Gen17.Chunk039R7
import Snaky.Gen17.Chunk039R8
import Snaky.Gen17.Chunk039R9
import Snaky.Gen17.Chunk039R10
import Snaky.Gen17.Chunk039R11
import Snaky.Gen17.Chunk039R12
import Snaky.Gen17.Chunk039R13
import Snaky.Gen17.Chunk039R14
import Snaky.CardsSound

namespace Snaky.Gen17

/-- Card 1736 is justified (checked in 16 pieces). -/
theorem t39_ok : t39.all (cardOK getK) = true :=
  CTree.all_leaf (cardOK_of_split (c1736_part0 ++ c1736_part1 ++ c1736_part2 ++ c1736_part3 ++ c1736_part4 ++ c1736_part5 ++ c1736_part6 ++ c1736_part7 ++ c1736_part8 ++ c1736_part9 ++ c1736_part10 ++ c1736_part11 ++ c1736_part12 ++ c1736_part13 ++ c1736_part14) c1736_head (by decide +kernel)
    (by simp only [List.all_append, c1736_r0, c1736_r1, c1736_r2, c1736_r3, c1736_r4, c1736_r5, c1736_r6, c1736_r7, c1736_r8, c1736_r9, c1736_r10, c1736_r11, c1736_r12, c1736_r13, c1736_r14, Bool.and_self]))

end Snaky.Gen17
