-- Generated by tools/cards2lean.py from third_party/sieben/cards-17x17.txt; do not edit.
import Snaky.Gen17.Tree

namespace Snaky.Gen17

def c1737_part7 : List Pt := [(7, 4), (7, 5), (7, 6), (7, 7), (7, 8), (7, 9), (7, 10), (7, 11), (7, 12), (7, 13), (7, 14), (7, 15), (7, 16), (8, 0), (8, 1)]

set_option maxHeartbeats 0 in
/-- Card 1737: White replies at 15 cells of its region (piece 8 of 17). -/
theorem c1737_r7 : c1737_part7.all (replyOK getK c1737) = true := by decide +kernel

end Snaky.Gen17
